import { Inter } from "next/font/google";
import "./globals.css";
import '../node_modules/bootstrap/dist/css/bootstrap.min.css'
import { AuthProvider } from "./providers";
import Navbar from "./Components/Navbar";
import Head from "next/head";
import App from "./index";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FlightSeems.com",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="node_modules/react-star-rating/dist/css/react-star-rating.min.css" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body className={inter.className} suppressHydrationWarning={true}>
        <App />
        <Navbar />
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
